version: "3"

services:

    plex:
        image: ghcr.io/linuxserver/plex
        container_name: PlexServer
        ports: 
        - "32400:32400"
        hostname: plexserver
        environment: 
          TZ: 'America/Argentina/Buenos_Aires'
          PUID: 1000
          PGID: 1000
        volumes:
        - ./Plex Library:/config/Library/Application Support/Plex Media Server
        #- ${PELICULAS}:/media/peliculas
        - ${ANIME}:/media/anime
        - ${ANIMEPELICULA}:/media/anime_pelicula
        #- ${DC}:/media/dc
        #- ${SERIES}:/media/series
        - ${ANIMEEXTENDS}:/media/anime_extends
        restart: always